# ==============================================================================
# ZC706 Time Tagger Constraints
# ==============================================================================
# Target: Xilinx ZC706 Evaluation Board (XC7Z045)
# ==============================================================================

# ==============================================================================
# Clock Constraints
# ==============================================================================

# The 200 MHz clock is generated by clk_wiz from FCLK_CLK1
# Primary clock from PS is defined in block design

# TDC clock (200 MHz from clock wizard)
# Note: Clock is already defined by clk_wiz IP XDC, no need to redefine
# The generated clock name is: clk_out1_system_clk_wiz_0_0

# AXI clock (100 MHz from PS)
# Already defined by PS7 block design automation

# ==============================================================================
# TDC Input - USER SMA CLOCK Connector (J36)
# ==============================================================================
# Using USER_SMA_CLOCK_P (J36) - Clock-capable MRCC pin for best TDC performance
#   - Pin H9 in HP Bank 34 (1.8V VCCO)
#   - LVCMOS18 for standard 0-1.8V pulse input
#
# ZC706 USER SMA connectors (XC7Z045-2FFG900):
#   J36 = USER_SMA_CLOCK_P = H9 (HP Bank 34, 1.8V, MRCC)
#   J35 = USER_SMA_CLOCK_N = G9 (HP Bank 34, 1.8V, MRCC)
#   J34 = USER_SMA_GPIO_P  = Y23 (HR Bank 11, 2.5V)
#   J33 = USER_SMA_GPIO_N  = Y24 (HR Bank 11, 2.5V)
#
# NOTE: Input signal must be 1.8V compatible (0V to 1.8V swing)
#       For higher voltage signals, use external level shifter or resistor divider
#       External 50-ohm termination recommended (LVCMOS18 does not support DCI)

# Primary TDC input - USER SMA GPIO P (J34)
# J34 = USER_SMA_GPIO_P = Y23 (Bank 11, 2.5V)
set_property PACKAGE_PIN Y23 [get_ports {tdc_hit_0}]
set_property IOSTANDARD LVCMOS25 [get_ports {tdc_hit_0}]
set_property PULLDOWN true [get_ports {tdc_hit_0}]

# Note: LVCMOS18 does not support internal termination (IN_TERM)
# Use external 50-ohm resistor to ground or series termination at source

# ==============================================================================
# Alternative Input Options (uncomment to use)
# ==============================================================================

# Option 2: USER_SMA_GPIO_P (J34) - HR Bank, 2.5V, no internal termination
# set_property PACKAGE_PIN Y23 [get_ports tdc_hit_0]
# set_property IOSTANDARD LVCMOS25 [get_ports tdc_hit_0]

# Option 3: FMC HPC LA00_CC_P - Clock-capable, requires FMC card
# set_property PACKAGE_PIN AF20 [get_ports tdc_hit_0]
# set_property IOSTANDARD LVCMOS25 [get_ports tdc_hit_0]

# ==============================================================================
# TDC Timing Constraints
# ==============================================================================

# The TDC hit input is asynchronous - set false path for timing
set_false_path -from [get_ports tdc_hit_0]

# ==============================================================================
# TDC Placement Constraints (CARRY4 Chain)
# ==============================================================================
# Place the CARRY4 chain in a single column for consistent delay
# Adjust SLICE location based on your floorplan needs

# Lock the first CARRY4 to a specific location
# The rest of the chain will propagate upward automatically
# Note: Update the path based on your actual hierarchy after synthesis
# set_property LOC SLICE_X50Y100 [get_cells tdc_ch0/tdc_chain[0].carry4_inst]

# Prevent optimization of the delay chain
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME =~ *tdc_chain*}]

# ==============================================================================
# Debug Outputs (optional - directly to GPIO header)
# ==============================================================================
# ZC706 Pmod J58 Header (directly connected to PL)
# Useful for oscilloscope debugging

# set_property PACKAGE_PIN AB14 [get_ports dbg_ts_valid]
# set_property IOSTANDARD LVCMOS25 [get_ports dbg_ts_valid]
# set_property PACKAGE_PIN AA14 [get_ports dbg_overflow]
# set_property IOSTANDARD LVCMOS25 [get_ports dbg_overflow]

# ==============================================================================
# LED Outputs (optional - directly to board LEDs)
# ==============================================================================
# ZC706 User LEDs (accent LEDs directly connected to PL)
# GPIO_LED[0] = Y21, GPIO_LED[1] = G2, GPIO_LED[2] = W21, GPIO_LED[3] = A17

# set_property PACKAGE_PIN Y21 [get_ports led_enable]
# set_property IOSTANDARD LVCMOS25 [get_ports led_enable]
# set_property PACKAGE_PIN G2 [get_ports led_overflow]
# set_property IOSTANDARD LVCMOS15 [get_ports led_overflow]

# ==============================================================================
# Cross-Clock Domain Constraints
# ==============================================================================

# Clock names from report_clocks:
#   clk_fpga_0                   - 100MHz AXI clock from PS7
#   clk_out1_system_clk_wiz_0_0  - 200MHz TDC clock from clk_wiz_0

# CDC between TDC domain (200MHz) and AXI domain (100MHz)
set_max_delay -datapath_only -from [get_clocks clk_out1_system_clk_wiz_0_0] -to [get_clocks clk_fpga_0] 8.000
set_max_delay -datapath_only -from [get_clocks clk_fpga_0] -to [get_clocks clk_out1_system_clk_wiz_0_0] 8.000

# ==============================================================================
# Additional FMC LPC Pins (for multi-channel expansion)
# ==============================================================================
# Uncomment and modify for additional TDC channels

# Channel 1: LA01_P = J20
# set_property PACKAGE_PIN J20 [get_ports tdc_hit_1]
# set_property IOSTANDARD LVCMOS25 [get_ports tdc_hit_1]

# Channel 2: LA02_P = L19  
# set_property PACKAGE_PIN L19 [get_ports tdc_hit_2]
# set_property IOSTANDARD LVCMOS25 [get_ports tdc_hit_2]

# Channel 3: LA03_P = N19
# set_property PACKAGE_PIN N19 [get_ports tdc_hit_3]
# set_property IOSTANDARD LVCMOS25 [get_ports tdc_hit_3]

# Channel 4: LA04_P = N20
# set_property PACKAGE_PIN N20 [get_ports tdc_hit_4]
# set_property IOSTANDARD LVCMOS25 [get_ports tdc_hit_4]
